### ISSUE TITLE
Adapt for smaller devices

### ISSUE THREAD

**Issue by tjodalv2k** [mortea15/BrewSource#12]
### Screens that should be adapted
- <s>Sign Up</s>
- <s>Sign In</s>
- <s>User Administration (Table)</s>
- <s>Edit Profile</s>
- <s>Brewery list (Table)</s>
- <s>Edit Brewery</s>
- About Us
- <s>Add br below "Save"-button in Edit Profile</s>

**Comment by mortea15** [comment]
#### Partially fixed.
Fixed as of now:
- Sign Up
- Sign In
- Break below "Save"-button in Edit Profile

**Comment by mortea15** [comment]
#### Partially fixed.
Fixed as of now:
- User Administration
- Edit Profile
- Brewery list
- Edit Brewery

**Comment by mortea15** [comment]
Fixed as of #13
